- hosts: localhost
  gather_facts: no
  become: yes
  connection: local
  collections:
    - community.docker
    - kubernetes.core
  vars:
    customnamespace: default
  tasks:
    - name: Pull industryproject image
      community.docker.docker_image:
        name: dsrivijaya/industryapp:{{ build_number }}
        source: pull
    - name: Create a Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: industryapp-k8s-deployment
            namespace: "{{ customnamespace }}"
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: industryapp
            template:
              metadata:
                labels:
                  app: industryapp
              spec:
                containers:
                - name: industryapp-container
                  image: dsrivijaya/industryapp:{{ build_number }}
                  ports:
                  - containerPort: 80
        namespace: "{{ customnamespace }}"
      register: deployment_out

    - name: Create a Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: industryapp-nodeportservice
            namespace: "{{ customnamespace }}"
          spec:
            type: NodePort
            selector:
              app: industryapp
            ports:
            - name: http
              port: 80
              targetPort: 8080
        namespace: "{{ customnamespace }}"
      register: service_out

    - name: Debug Container Output
      debug:
        var: container_out

    - name: Debug Deployment Output
      debug:
        var: deployment_out

    - name: Debug Service Output
      debug:
        var: service_out
